### ISSUE TITLE
Strings containing decimals are converted into negative numbers

### ISSUE THREAD

**Issue by travs** [melonproject/token-math#12]
```
x = new BN("0.1");
console.log(String(x));    // '-19'
```

Not sure how thick you wanted to wrap BN.js but this just tripped me up.
I'm suggesting we throw on decimal input, but not sure where to put it (BigInteger.ts class shouldn't be extended right?)

**Comment by schmidsi** [comment]
Actually, I think the constructor of BigInteger is the right place for a check like this.
